import { summarize, toCsv } from './parser.js';
const state = { devices: [], selected: null, tab: 'summary' }; const $ = selector => document.querySelector(selector);
const worker = new Worker('./worker.js', { type: 'module' });
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const download = (content, filename, type) => { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); };
function showNotice(message, kind = 'info') { const notice = $('#notice'); notice.textContent = message; notice.className = `notice ${kind}`; setTimeout(() => notice.classList.add('hidden'), 6000); }
function setProgress(done, total) { $('#progressWrap').classList.remove('hidden'); $('#progressBar').style.width = `${total ? done / total * 100 : 0}%`; $('#progressCount').textContent = `${done} / ${total}`; $('#progressLabel').textContent = done === total ? 'Анализ завершён' : 'Разбор конфигураций в Worker...'; }
function ingest(files) { const selected = [...files].filter(file => /\.(cfg|conf|txt)$/i.test(file.name)); if (!selected.length) return showNotice('Выберите конфигурации .cfg, .conf или .txt', 'warning'); state.devices = []; render(); setProgress(0, selected.length); worker.postMessage({ files: selected }); }
worker.onmessage = ({ data }) => { if (data.type === 'progress') return setProgress(data.done, data.total); state.devices = data.devices; populateVendors(); render(); setProgress(state.devices.length, state.devices.length); $('#exportJson').disabled = $('#exportCsv').disabled = false; showNotice(`Обработано конфигураций: ${state.devices.length}`, 'success'); };
$('#fileInput').onchange = event => ingest(event.target.files); $('#folderInput').onchange = event => ingest(event.target.files);
const dropZone = $('#dropZone'); ['dragenter', 'dragover'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.remove('dragging'); })); dropZone.addEventListener('drop', event => ingest(event.dataTransfer.files));
function populateVendors() { const vendors = [...new Set(state.devices.map(device => device.vendor.value))].sort(); $('#vendorFilter').innerHTML = '<option value="all">Все вендоры</option>' + vendors.map(vendor => `<option>${escapeHtml(vendor)}</option>`).join(''); }
function filtered() { const query = $('#searchInput').value.toLowerCase(); const vendor = $('#vendorFilter').value; const status = $('#statusFilter').value; return state.devices.filter(device => (!query || JSON.stringify(device).toLowerCase().includes(query)) && (vendor === 'all' || device.vendor.value === vendor) && (status === 'all' || device.status === status)); }
function render() { const stats = summarize(state.devices); $('#kpiDevices').textContent = stats.devices; $('#kpiHealthy').textContent = stats.devices ? `${Math.round(stats.healthy / stats.devices * 100)}%` : '—'; $('#kpiVlans').textContent = stats.vlans; $('#kpiAttention').textContent = stats.attention; const rows = filtered(); $('#resultCount').textContent = `${rows.length} results`; $('#deviceRows').innerHTML = rows.length ? rows.map((device, index) => `<button class="device-row" data-id="${escapeHtml(device.id)}"><span class="device-name"><b>${escapeHtml(device.hostname.value)}</b><small>${escapeHtml(device.source)} · ${formatBytes(device.bytes)}</small></span><span>${escapeHtml(device.vendor.value)}<small>${escapeHtml(device.model.value)}</small></span><span class="mono">${device.ports.length || '—'}</span><span class="mono">${device.vlans.length || '—'}</span><span class="control-dots">${Object.values(device.settings).map(setting => `<i class="${setting.enabled ? 'on' : ''}" title="${setting.label}"></i>`).join('')}</span><span class="status ${device.status}">${device.status === 'healthy' ? 'Healthy' : 'Attention'}</span></button>`).join('') : '<div class="empty-state"><span>⌕</span><b>Ничего не найдено</b><small>Измените фильтры или загрузите конфигурации</small></div>'; document.querySelectorAll('.device-row').forEach(row => row.onclick = () => openDetail(state.devices.find(device => device.id === row.dataset.id))); }
const formatBytes = bytes => bytes > 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`;
['searchInput', 'vendorFilter', 'statusFilter'].forEach(id => $(`#${id}`).addEventListener('input', render)); $('#exportJson').onclick = () => download(JSON.stringify(state.devices, null, 2), 'l2-dcp-export.json', 'application/json'); $('#exportCsv').onclick = () => download(toCsv(state.devices), 'l2-dcp-export.csv', 'text/csv');
function openDetail(device) { state.selected = device; state.tab = 'summary'; $('#detailPanel').classList.remove('hidden'); $('#detailTitle').textContent = device.hostname.value; $('#detailSubtitle').textContent = `${device.vendor.value} · ${device.model.value} · ${device.source}`; $('#detailConfidence').textContent = device.vendor.confidence === 'unknown' ? '⚠ LOW CONFIDENCE' : '✓ HEURISTIC MATCH'; document.querySelectorAll('.tab').forEach(tab => tab.classList.toggle('active', tab.dataset.tab === state.tab)); renderDetail(); $('#detailPanel').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function renderDetail() { const d = state.selected; if (!d) return; const body = $('#detailBody'); const cards = Object.values(d.settings).map(setting => `<div class="setting-card"><span class="setting-state ${setting.enabled ? 'enabled' : 'unknown'}">${setting.enabled ? 'DETECTED' : 'NOT FOUND'}</span><b>${setting.label}</b><small>${setting.entries.length ? escapeHtml(setting.entries.slice(0, 2).join(' · ')) : 'Нет уверенного совпадения в конфигурации'}</small></div>`).join(''); if (state.tab === 'summary') body.innerHTML = `<div class="summary-grid"><div class="summary-stat"><span>PORTS</span><b>${d.ports.length}</b><small>распознано</small></div><div class="summary-stat"><span>VLANs</span><b>${d.vlans.length}</b><small>${d.vlans.slice(0, 5).map(v => v.id).join(', ') || 'unknown'}</small></div><div class="summary-stat"><span>WARNINGS</span><b>${d.warnings.length}</b><small>сигналов внимания</small></div><div class="summary-stat"><span>UNKNOWN</span><b>${d.unknown.length}</b><small>директив</small></div></div><h3>Контрольные функции</h3><div class="settings-grid">${cards}</div>${d.warnings.length ? `<div class="warning-list">${d.warnings.map(warning => `⚠ ${escapeHtml(warning)}`).join('<br>')}</div>` : ''}`; else if (state.tab === 'ports') body.innerHTML = `<h3>Распознанные интерфейсы <span class="muted">${d.ports.length}</span></h3>${d.ports.length ? `<div class="mini-table">${d.ports.map(port => `<div><span class="mono">${escapeHtml(port.name)}</span><span>${port.mode}</span><span>${port.vlan || '—'}</span><span>${port.speed || 'auto'}</span><span class="status-dot ${port.state}">${port.state}</span></div>`).join('')}</div>` : '<div class="inline-empty">Интерфейсы не распознаны уверенно.</div>'}`; else if (state.tab === 'vlans') body.innerHTML = `<h3>VLAN inventory <span class="muted">${d.vlans.length}</span></h3><div class="tag-cloud">${d.vlans.map(vlan => `<span class="vlan-tag"><b>${vlan.id}</b>${vlan.name ? escapeHtml(vlan.name) : 'unnamed'} <small>${vlan.confidence}</small></span>`).join('') || '<div class="inline-empty">VLAN не найдены.</div>'}</div>`; else if (state.tab === 'controls') body.innerHTML = `<h3>Security & control plane</h3><div class="settings-grid">${cards}</div>`; else body.innerHTML = `<h3>Неизвестные директивы <span class="muted">${d.unknown.length}</span></h3><div class="unknown-list">${d.unknown.map(item => `<code>${escapeHtml(item)}</code>`).join('') || '<div class="inline-empty">Неизвестных строк не найдено.</div>'}</div>`; }
document.querySelectorAll('.tab').forEach(tab => tab.onclick = () => { state.tab = tab.dataset.tab; document.querySelectorAll('.tab').forEach(item => item.classList.toggle('active', item === tab)); renderDetail(); }); $('#closeDetail').onclick = () => $('#detailPanel').classList.add('hidden'); $('#analyzeButton').onclick = async () => { const endpoint = $('#endpointInput').value.trim(); const output = $('#agentOutput'); const d = state.selected; if (!d) return; output.classList.remove('hidden'); if (!endpoint) { output.textContent = `Локальное резюме\n\n${d.hostname.value}: ${d.vendor.value}, ${d.ports.length} портов, ${d.vlans.length} VLAN.\nСигналы: ${d.warnings.length ? d.warnings.join('; ') : 'критичных предупреждений нет'}.\n\nВведите endpoint шлюза, чтобы отправить нормализованный JSON. Ключи в браузере не хранятся.`; return; } try { output.textContent = 'Запрос к указанному endpoint...'; const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ device: d }) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); output.textContent = JSON.stringify(await response.json(), null, 2); } catch (error) { output.textContent = `Endpoint недоступен: ${error.message}. Исходная конфигурация не отправлялась на другой адрес.`; } };
render();
