import { summarize, toCsv } from './parser.js';
import { createDemoDevices } from './demo-configs.js';
import { analyzeWithLlm, buildAnalysisPayload, getConfiguredEndpoint } from './llm-adapter.js';
import { paginate } from './pagination.js';

const state = { devices: createDemoDevices(), selected: null, tab: 'summary', page: 1, requestId: 0 };
const $ = selector => document.querySelector(selector);
const worker = new Worker('./worker.js', { type: 'module' });
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const download = (content, filename, type) => { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url); };
function showNotice(message, kind = 'info') { const notice = $('#notice'); notice.textContent = message; notice.className = `notice ${kind}`; setTimeout(() => notice.classList.add('hidden'), 6000); }
function setProgress(done, total) { $('#progressWrap').classList.remove('hidden'); $('#progressBar').style.width = `${total ? done / total * 100 : 0}%`; $('#progressCount').textContent = `${done} / ${total}`; $('#progressLabel').textContent = done === total ? 'Анализ завершён' : 'Разбор конфигураций в Worker...'; }
function ingest(files) { const selected = [...files].filter(file => /\.(cfg|conf|txt)$/i.test(file.name)); if (!selected.length) return showNotice('Выберите конфигурации .cfg, .conf или .txt', 'warning'); state.devices = []; state.page = 1; state.selected = null; $('#detailPanel').classList.add('hidden'); $('#analyzeSelected').disabled = true; render(); setProgress(0, selected.length); worker.postMessage({ files: selected, requestId: ++state.requestId }); }
worker.onmessage = ({ data }) => { if (data.requestId !== state.requestId) return; if (data.type === 'progress') return setProgress(data.done, data.total); state.devices = data.devices; populateVendors(); render(); setProgress(state.devices.length, state.devices.length); $('#exportJson').disabled = $('#exportCsv').disabled = false; showNotice(data.demo ? 'Загружено 50 синтетических demo-конфигураций' : `Обработано конфигураций: ${state.devices.length}`, 'success'); };
worker.onerror = () => { $('#progressWrap').classList.add('hidden'); showNotice('Не удалось обработать конфигурации в Worker', 'error'); };
$('#fileInput').onchange = event => ingest(event.target.files); $('#folderInput').onchange = event => ingest(event.target.files);
const dropZone = $('#dropZone'); ['dragenter', 'dragover'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.add('dragging'); })); ['dragleave', 'drop'].forEach(type => dropZone.addEventListener(type, event => { event.preventDefault(); dropZone.classList.remove('dragging'); })); dropZone.addEventListener('drop', event => ingest(event.dataTransfer.files));
function populateVendors() { const vendors = [...new Set(state.devices.map(device => device.vendor.value))].sort(); $('#vendorFilter').innerHTML = '<option value="all">Все вендоры</option>' + vendors.map(vendor => `<option>${escapeHtml(vendor)}</option>`).join(''); }
function filtered() { const query = $('#searchInput').value.toLowerCase(); const vendor = $('#vendorFilter').value; const status = $('#statusFilter').value; return state.devices.filter(device => (!query || JSON.stringify(device).toLowerCase().includes(query)) && (vendor === 'all' || device.vendor.value === vendor) && (status === 'all' || device.status === status)); }
function renderPagination(pageCount, currentPage) { const pagination = $('#pagination'); pagination.innerHTML = pageCount > 1 ? `<button class="pagination-button" data-page="${currentPage - 1}" ${currentPage === 1 ? 'disabled' : ''}>Назад</button><span class="pagination-pages">${Array.from({ length: pageCount }, (_, index) => `<button class="pagination-button ${index + 1 === currentPage ? 'active' : ''}" data-page="${index + 1}">${index + 1}</button>`).join('')}</span><button class="pagination-button" data-page="${currentPage + 1}" ${currentPage === pageCount ? 'disabled' : ''}>Вперёд</button>` : ''; }
function render() { const stats = summarize(state.devices); $('#kpiDevices').textContent = stats.devices; $('#kpiHealthy').textContent = stats.devices ? `${Math.round(stats.healthy / stats.devices * 100)}%` : '—'; $('#kpiVlans').textContent = stats.vlans; $('#kpiAttention').textContent = stats.attention; const rows = filtered(); const page = paginate(rows, state.page); state.page = page.currentPage; $('#resultCount').textContent = `${rows.length} results`; renderPagination(page.pageCount, page.currentPage); $('#deviceRows').innerHTML = page.items.length ? page.items.map(device => `<button class="device-row" data-id="${escapeHtml(device.id)}"><span class="device-name"><b>${escapeHtml(device.hostname.value)}${device.origin === 'synthetic-demo' ? ' <em class="demo-badge">DEMO</em>' : ''}</b><small>${escapeHtml(device.source)} · ${formatBytes(device.bytes)}</small></span><span>${escapeHtml(device.vendor.value)}<small>${escapeHtml(device.model.value)}</small></span><span class="mono">${device.ports.length || '—'}</span><span class="mono">${device.vlans.length || '—'}</span><span class="control-dots">${Object.values(device.settings).map(setting => `<i class="${setting.enabled ? 'on' : ''}" title="${escapeHtml(setting.label)}"></i>`).join('')}</span><span class="status ${device.status}">${device.status === 'healthy' ? 'Healthy' : 'Attention'}</span></button>`).join('') : '<div class="empty-state"><span>⌕</span><b>Ничего не найдено</b><small>Измените фильтры или загрузите конфигурации</small></div>'; document.querySelectorAll('.device-row').forEach(row => row.onclick = () => openDetail(state.devices.find(device => device.id === row.dataset.id))); }
const formatBytes = bytes => bytes > 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`;
['searchInput', 'vendorFilter', 'statusFilter'].forEach(id => $(`#${id}`).addEventListener('input', () => { state.page = 1; render(); })); $('#pagination').onclick = event => { const button = event.target.closest('[data-page]'); if (!button || button.disabled) return; state.page = Number(button.dataset.page); render(); }; $('#exportJson').onclick = () => download(JSON.stringify(state.devices, null, 2), 'l2-dcp-export.json', 'application/json'); $('#exportCsv').onclick = () => download(toCsv(state.devices), 'l2-dcp-export.csv', 'text/csv');
function openDetail(device) { state.selected = device; state.tab = 'summary'; $('#detailPanel').classList.remove('hidden'); $('#analyzeSelected').disabled = false; $('#detailTitle').textContent = device.hostname.value; $('#detailSubtitle').textContent = `${device.vendor.value} · ${device.model.value} · ${device.source}`; $('#detailConfidence').textContent = device.vendor.confidence === 'unknown' ? '⚠ LOW CONFIDENCE' : '✓ HEURISTIC MATCH'; document.querySelectorAll('.tab').forEach(tab => tab.classList.toggle('active', tab.dataset.tab === state.tab)); renderDetail(); $('#detailPanel').scrollIntoView({ behavior: 'smooth', block: 'start' }); }
function renderDetail() { const d = state.selected; if (!d) return; const body = $('#detailBody'); const cards = Object.values(d.settings).map(setting => `<div class="setting-card"><span class="setting-state ${setting.enabled ? 'enabled' : 'unknown'}">${setting.enabled ? 'DETECTED' : 'NOT FOUND'}</span><b>${escapeHtml(setting.label)}</b><small>${setting.entries.length ? escapeHtml(setting.entries.slice(0, 2).join(' · ')) : 'Нет уверенного совпадения в конфигурации'}</small></div>`).join(''); if (state.tab === 'summary') body.innerHTML = `<div class="summary-grid"><div class="summary-stat"><span>PORTS</span><b>${d.ports.length}</b><small>распознано</small></div><div class="summary-stat"><span>VLANs</span><b>${d.vlans.length}</b><small>${d.vlans.slice(0, 5).map(v => v.id).join(', ') || 'unknown'}</small></div><div class="summary-stat"><span>WARNINGS</span><b>${d.warnings.length}</b><small>сигналов внимания</small></div><div class="summary-stat"><span>UNKNOWN</span><b>${d.unknown.length}</b><small>директив</small></div></div><h3>Контрольные функции</h3><div class="settings-grid">${cards}</div>${d.warnings.length ? `<div class="warning-list">${d.warnings.map(warning => `⚠ ${escapeHtml(warning)}`).join('<br>')}</div>` : ''}`; else if (state.tab === 'ports') body.innerHTML = `<h3>Распознанные интерфейсы <span class="muted">${d.ports.length}</span></h3>${d.ports.length ? `<div class="mini-table">${d.ports.map(port => `<div><span class="mono">${escapeHtml(port.name)}</span><span>${port.mode}</span><span>${port.vlan || '—'}</span><span>${port.speed || 'auto'}</span><span class="status-dot ${port.state}">${port.state}</span></div>`).join('')}</div>` : '<div class="inline-empty">Интерфейсы не распознаны уверенно.</div>'}`; else if (state.tab === 'vlans') body.innerHTML = `<h3>VLAN inventory <span class="muted">${d.vlans.length}</span></h3><div class="tag-cloud">${d.vlans.map(vlan => `<span class="vlan-tag"><b>${vlan.id}</b>${vlan.name ? escapeHtml(vlan.name) : 'unnamed'} <small>${vlan.confidence}</small></span>`).join('')}</div>`; else if (state.tab === 'controls') body.innerHTML = `<h3>Контрольные функции</h3><div class="settings-grid">${cards}</div>`; else body.innerHTML = `<h3>Неизвестные директивы <span class="muted">${d.unknown.length}</span></h3><div class="unknown-list">${d.unknown.map(item => `<code>${escapeHtml(item)}</code>`).join('')}</div>`; }
document.querySelectorAll('.tab').forEach(tab => tab.onclick = () => { state.tab = tab.dataset.tab; document.querySelectorAll('.tab').forEach(item => item.classList.toggle('active', item === tab)); renderDetail(); }); $('#closeDetail').onclick = () => { $('#detailPanel').classList.add('hidden'); state.selected = null; $('#analyzeSelected').disabled = true; };
const llmStatus = $('#llmStatus'); const llmOutput = $('#llmOutput');
async function runAnalysis(selected = null) { llmStatus.textContent = 'Анализ выполняется...'; llmStatus.className = 'llm-status loading'; llmOutput.textContent = ''; try { const result = await analyzeWithLlm(buildAnalysisPayload(state.devices, selected)); llmStatus.textContent = result.mode === 'local' && !getConfiguredEndpoint() ? 'LLM endpoint не настроен. Показан локальный demo fallback.' : 'Ответ получен через настроенный backend proxy.'; llmStatus.className = 'llm-status success'; llmOutput.textContent = result.text; } catch (error) { llmStatus.textContent = `Ошибка анализа: ${error.message}`; llmStatus.className = 'llm-status error'; llmOutput.textContent = 'Проверьте endpoint, CORS и доступность backend proxy. Исходные конфигурации не отправлялись.'; } }
$('#analyzeSummary').onclick = () => runAnalysis(); $('#analyzeSelected').onclick = () => runAnalysis(state.selected);
populateVendors(); render(); $('#exportJson').disabled = $('#exportCsv').disabled = false;
